variables:
  ANONYMIZATION_UI_IMAGE_NAME: gitlab.cosmian.com:5000/core/anonymization_ui:latest

stages:
  - build
  - test
  - deploy

build_and_push:
  stage: build
  tags: [shell]
  only: [main, develop, tags]
  cache: {}
  before_script:
    - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.cosmian.com/core/anonymization_ui.git
    - cd anonymization_ui
  script:
    - ./scripts/build_push.sh

test_e2e:
  stage: test
  tags: [shell]
  only: [main, develop, tags, merge_requests]
  before_script:
    - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.cosmian.com/core/anonymization_ui.git
    - cd anonymization_ui
    - git checkout ${CI_COMMIT_REF_NAME}
  script:
    - ./scripts/build_test_e2e.sh
