/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_quoteheader_free(a: number): void;
export function __wbg_get_quoteheader_version(a: number): number;
export function __wbg_set_quoteheader_version(a: number, b: number): void;
export function __wbg_get_quoteheader_att_key_type(a: number): number;
export function __wbg_set_quoteheader_att_key_type(a: number, b: number): void;
export function __wbg_get_quoteheader_reserved(a: number): number;
export function __wbg_set_quoteheader_reserved(a: number, b: number): void;
export function __wbg_get_quoteheader_qe_svn(a: number): number;
export function __wbg_set_quoteheader_qe_svn(a: number, b: number): void;
export function __wbg_get_quoteheader_pce_svn(a: number): number;
export function __wbg_set_quoteheader_pce_svn(a: number, b: number): void;
export function __wbg_get_quoteheader_vendor_id(a: number, b: number): void;
export function __wbg_set_quoteheader_vendor_id(a: number, b: number, c: number): void;
export function __wbg_get_quoteheader_user_data(a: number, b: number): void;
export function __wbg_set_quoteheader_user_data(a: number, b: number, c: number): void;
export function __wbg_reportbody_free(a: number): void;
export function __wbg_get_reportbody_cpu_svn(a: number, b: number): void;
export function __wbg_set_reportbody_cpu_svn(a: number, b: number, c: number): void;
export function __wbg_get_reportbody_misc_select(a: number): number;
export function __wbg_set_reportbody_misc_select(a: number, b: number): void;
export function __wbg_get_reportbody_reserved1(a: number, b: number): void;
export function __wbg_set_reportbody_reserved1(a: number, b: number, c: number): void;
export function __wbg_get_reportbody_isv_ext_prod_id(a: number, b: number): void;
export function __wbg_set_reportbody_isv_ext_prod_id(a: number, b: number, c: number): void;
export function __wbg_get_reportbody_flags(a: number): number;
export function __wbg_set_reportbody_flags(a: number, b: number): void;
export function __wbg_get_reportbody_xfrm(a: number): number;
export function __wbg_set_reportbody_xfrm(a: number, b: number): void;
export function __wbg_get_reportbody_mr_enclave(a: number, b: number): void;
export function __wbg_set_reportbody_mr_enclave(a: number, b: number, c: number): void;
export function __wbg_get_reportbody_reserved2(a: number, b: number): void;
export function __wbg_set_reportbody_reserved2(a: number, b: number, c: number): void;
export function __wbg_get_reportbody_mr_signer(a: number, b: number): void;
export function __wbg_set_reportbody_mr_signer(a: number, b: number, c: number): void;
export function __wbg_get_reportbody_reserved3(a: number, b: number): void;
export function __wbg_set_reportbody_reserved3(a: number, b: number, c: number): void;
export function __wbg_get_reportbody_config_id(a: number, b: number): void;
export function __wbg_set_reportbody_config_id(a: number, b: number, c: number): void;
export function __wbg_get_reportbody_isv_prod_id(a: number): number;
export function __wbg_set_reportbody_isv_prod_id(a: number, b: number): void;
export function __wbg_get_reportbody_isv_svn(a: number): number;
export function __wbg_set_reportbody_isv_svn(a: number, b: number): void;
export function __wbg_get_reportbody_config_svn(a: number): number;
export function __wbg_set_reportbody_config_svn(a: number, b: number): void;
export function __wbg_get_reportbody_reserved4(a: number, b: number): void;
export function __wbg_set_reportbody_reserved4(a: number, b: number, c: number): void;
export function __wbg_get_reportbody_isv_family_id(a: number, b: number): void;
export function __wbg_set_reportbody_isv_family_id(a: number, b: number, c: number): void;
export function __wbg_get_reportbody_report_data(a: number, b: number): void;
export function __wbg_set_reportbody_report_data(a: number, b: number, c: number): void;
export function __wbg_quote_free(a: number): void;
export function __wbg_get_quote_header(a: number): number;
export function __wbg_set_quote_header(a: number, b: number): void;
export function __wbg_get_quote_report_body(a: number): number;
export function __wbg_set_quote_report_body(a: number, b: number): void;
export function quote_new(a: number, b: number, c: number): void;
export function quote_from_pem_certificate(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
